---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

# From http://eric.clst.org/Stuff/USGeoJSON and
# https://en.wikipedia.org/wiki/List_of_United_States_counties_and_county_equivalents


library(ggplot2)
library(dplyr)
library(leaflet)
library(rgdal)

#natlClaims <- read.csv("~/opioid-reboot/natlClaims.csv")
#stateAbbrev <- read.csv("~/opioid-reboot/stateAbbrev.csv")

OpiClaimsbyState <- natlClaims %>%
  group_by(ProviderState) %>%
  summarise(TotalClaims = sum(TotalClaimCount))


#View(OpiClaimsbyState)

names(OpiClaimsbyState)[names(OpiClaimsbyState) == 'ProviderState'] <- 'X1'
OpiState <- left_join(OpiClaimsbyState, stateAbbrev, by = "X1")


write.table(OpiState, file = "ClaimsbyState.txt")
names(OpiState)[names(OpiState) == 'State'] <- 'NAME'



map  <- rgdal::readOGR("gz_2010_us_040_00_5m.json", "OGRGeoJSON")
data <- read.table("ClaimsbyState.txt")
```

```{r}
merged   <- left_join(map@data, data, by = c("NAME" = "State"))
map@data <- merged
#write.table(merged, file = "merged.txt")
```


```{r}
library(leaflet)

bins <- c(0,100000,500000,1000000,1500000,2500000,5000000,Inf)
pal  <- colorBin("YlOrRd", map@data$TotalClaims, bins=bins)

  
leaflet(data = map) %>%
  setView(-96, 37.8, 4) %>%
  addTiles()        %>%
  addPolygons(
    fillColor = ~pal(TotalClaims),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7)
    highlight = highlightOptions(
    weight = 5,
    color = "#666",
    dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE)
    label = labels
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto")

```